# Generated by Django 3.1.1 on 2020-11-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_add_cart_contact_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='preference',
            field=models.CharField(blank=True, choices=[('Vegetarian', 'Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
