# Generated by Django 3.1.1 on 2020-11-06 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('state_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.state')),
            ],
        ),
    ]
