# Generated by Django 3.1.1 on 2020-11-07 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0009_auto_20201107_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_cart',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='add_cart',
            name='customer_id',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='add_cart',
            name='food_id',
        ),
        migrations.AddField(
            model_name='add_cart',
            name='food_id',
            field=models.ManyToManyField(null=True, to='store.Foods'),
        ),
    ]
