# Generated by Django 3.1.1 on 2020-11-08 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0012_auto_20201108_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_cart',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='add_cart',
            name='food_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display', to='store.foods'),
        ),
        migrations.AlterField(
            model_name='add_cart',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='add_cart',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
