# Generated by Django 3.1.1 on 2020-11-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20201109_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
