# Generated by Django 3.1.1 on 2020-11-09 05:32

import django.contrib.auth.models
from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20201109_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_cart',
            name='user_id',
            field=models.IntegerField(null=True, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='add_cart',
            name='foods',
            field=models.IntegerField(null=True, verbose_name=store.models.Foods),
        ),
    ]
