# Generated by Django 3.1.1 on 2020-11-09 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0021_auto_20201109_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_cart',
            name='foods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.foods'),
        ),
        migrations.AlterField(
            model_name='add_cart',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
